#include <stdio.h>
#include <stdlib.h>
#include <ctype.h>

#define ENUM_PREFIX "TAG_"
// The range of HTML basic ASCII characters, a-z A-Z 0-9 < > ; : / ?
#define FIRST_CHAR 47 // '/'
#define LAST_CHAR 122 // 'z'

void
str_to_sym( char* str ) {
    while( *str != 0 ) {
        if( *str == '-' || *str == '.' || *str == '/' )
            *str = '_';
        else
            *str =toupper(*str);
        str++;
    }
}

int
main( int argc, char** argv ) {
    if( argc != 4 ) {
        fprintf( stderr, "Usage: gen_tags <file containing tagnames> <output header-file> <output fsm-file>\n" );
        return -1;
    }

    enum FILES {
        TAG_FILE,
        HEADER_FILE,
        FSM_FILE
    };

    // Lets open all three files!

    FILE *files[3];

    for( int i =0; i < 3; i++ ) {
        files[i] =fopen( argv[i+1], i==0 ? "r" : "w" );
        if( !files[i]) {
            fprintf( stderr, "ERROR: Could not open `%s'\n", argv[i+1] );
            return -1;
        }
    }

    // Write some usefull headers
    
    for( int i =1; i <3; i++ ) {
        fprintf( files[i], "\
/* This file was automatically generated by gen_tags.c from `%s' \n\
 * Please do not edit this file in any way \n\
 */\n\n", argv[1] );
    }

    fprintf( files[FSM_FILE], "#include \"%s\"\n", argv[2] );
    fprintf( files[FSM_FILE], "%%! %s_N %d\n\n", ENUM_PREFIX, LAST_CHAR - FIRST_CHAR );
    fprintf( files[FSM_FILE], "**, ** => { %sUNKNOWN }\n\n", ENUM_PREFIX );
    str_to_sym( argv[2] );
    fprintf( files[HEADER_FILE], "#ifndef %s\n", argv[2] );
    fprintf( files[HEADER_FILE], "#define %s\n\n", argv[2] );
    fprintf( files[HEADER_FILE], "#define %sNONE 0\n", ENUM_PREFIX );

    // Read the tags from the tag-file
    // For each tag, we output a #define to the header file
    // and a matching transition to the fsm file

    int n_tags =0;

    while( !feof( files[TAG_FILE] ) ) {

        char* tag =NULL;
        fscanf( files[TAG_FILE], "%ms", &tag );
        if( !tag ) break;

        // Transition
        fprintf( files[FSM_FILE], "%sNONE, \"%s%c\"i => ",
                ENUM_PREFIX,
                tag,
                FIRST_CHAR );

        str_to_sym( tag );
        
        fprintf( files[FSM_FILE], "{ %s%s }\n",
                ENUM_PREFIX,
                tag );

        // Header #define
        fprintf( files[HEADER_FILE], "#define %s%s %d\n", 
                ENUM_PREFIX, tag, ++n_tags );


        free( tag );
    }

    // Write the UNKNOWN and `count' macros

    fprintf( files[HEADER_FILE], "#define %sUNKNOWN %d\n\n", ENUM_PREFIX, ++n_tags );
    fprintf( files[HEADER_FILE], "#define %s_N %d\n", ENUM_PREFIX, ++n_tags );
    fprintf( files[HEADER_FILE], "#define %s_N_INPUTS %d\n", ENUM_PREFIX, LAST_CHAR - FIRST_CHAR );
    fprintf( files[HEADER_FILE], "#define %s_EOF %d\n", ENUM_PREFIX, 0 );
    fprintf( files[HEADER_FILE], "#define %s_FIRST_CHAR %d\n", ENUM_PREFIX, FIRST_CHAR );
    fprintf( files[HEADER_FILE], "#define %s_LAST_CHAR %d\n/* */\n", ENUM_PREFIX, LAST_CHAR );
    fprintf( files[HEADER_FILE], "#endif\n" );

    // Cleanup and exit

    for( int i =0; i < 3; i++ ) fclose( files[i] );
    return 0;
}
