/* This file was automatically generated by gen_entities.c from `entities.json' 
 * Please do not edit this file in any way 
 */

#ifndef ___SRC_ENTITY_H
#define ___SRC_ENTITY_H

#define ENTITY_NONE 0
#define ENTITY_UNKNOWN 1

#define ENTITY_SUCCESS_BIT 0x80000000

#define ENTITY__N 2126
#define ENTITY__N_INPUTS 63
#define ENTITY__EOF 0
#define ENTITY__FIRST_CHAR 59
#define ENTITY__LAST_CHAR 122
/* */
#endif
